# Generated by Django 3.2.18 on 2023-03-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200, verbose_name='gender')),
                ('masterCategory', models.CharField(max_length=200, verbose_name='masterCategory')),
                ('subCategory', models.CharField(max_length=200, verbose_name='subCategory')),
                ('articleType', models.CharField(max_length=200, verbose_name='articleType')),
                ('baseColour', models.CharField(max_length=200, verbose_name='baseColour')),
                ('season', models.CharField(max_length=200, verbose_name='season')),
                ('year', models.CharField(max_length=200, verbose_name='year')),
                ('usage', models.CharField(max_length=200, verbose_name='usage')),
                ('productDisplayName', models.CharField(max_length=200, verbose_name='productDisplayName')),
                ('imagePath', models.CharField(max_length=200, verbose_name='imagePath')),
            ],
        ),
    ]
