# Generated by Django 3.2.18 on 2023-03-13 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230310_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producttest')),
                ('recommended_products', models.ManyToManyField(related_name='recommended_from', to='store.ProductTest')),
            ],
        ),
    ]
