# Generated by Django 3.2.18 on 2023-03-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
