# Generated by Django 3.2.18 on 2023-03-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_recommendedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producttest')),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendedProduct',
        ),
    ]
