# Generated by Django 3.2.18 on 2023-03-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230313_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
