# Generated by Django 3.2.18 on 2023-03-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('masterCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('articleType', models.CharField(blank=True, max_length=200, null=True)),
                ('baseColour', models.CharField(blank=True, max_length=200, null=True)),
                ('season', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('usage', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference', to='store.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_preferences', to='store.userpreference'),
        ),
    ]
