# Generated by Django 3.2.18 on 2023-03-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230314_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='store.producttest'),
        ),
        migrations.AlterField(
            model_name='recommendedimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='store.producttest'),
        ),
    ]
