# Generated by Django 3.2.18 on 2023-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_recommendedimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='image_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
