# Generated by Django 3.2.18 on 2023-03-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_recommendedimage_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='related_product',
        ),
        migrations.AlterField(
            model_name='recommendedimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producttest'),
        ),
    ]
