# Generated by Django 3.2.18 on 2023-03-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_recommendedimage_related_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedimage',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.producttest'),
        ),
    ]
