# Generated by Django 3.2.18 on 2023-03-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_recommendedimage_related_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='related_product',
        ),
    ]
