# Generated by Django 3.2.18 on 2023-03-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_recommendedimage_related_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanRecommendedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mean_main_product', to='store.producttest')),
            ],
        ),
    ]
