# Generated by Django 3.2.18 on 2023-03-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_meanrecommendedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='store.producttest'),
        ),
        migrations.DeleteModel(
            name='MeanRecommendedImage',
        ),
    ]
