# Generated by Django 3.2.18 on 2023-03-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_recommendedimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='masterCategory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
