# Generated by Django 3.2.18 on 2023-03-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20230319_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='recommendedimage',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.producttest'),
        ),
    ]
