# Generated by Django 3.2.18 on 2023-03-27 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_recommendedimage_related_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='related_product',
        ),
        migrations.AddField(
            model_name='recommendedimage',
            name='product_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_images', to='store.producttest'),
        ),
    ]
