# Generated by Django 3.2.18 on 2023-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20230327_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='recCategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
