# Generated by Django 3.2.18 on 2023-03-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_recommendedimage_reccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='related_product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
