# Generated by Django 3.2.18 on 2023-03-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_recommendedimage_related_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='recCategory',
        ),
        migrations.RemoveField(
            model_name='recommendedimage',
            name='related_product_name',
        ),
    ]
