# Generated by Django 3.2.18 on 2023-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20230327_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='masterCategory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
