# Generated by Django 3.2.18 on 2023-03-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_recommendedimage_mastercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedimage',
            name='related_product_masterCategory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
