# Generated by Django 3.2.18 on 2023-03-28 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_recommendedimage_related_product_mastercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanCartRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('masterCategory', models.CharField(max_length=200, null=True)),
                ('related_product_masterCategory', models.CharField(max_length=200, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mean_cart_recommendations', to='store.order')),
            ],
        ),
    ]
