# Generated by Django 3.2.18 on 2023-03-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_meancartrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.DeleteModel(
            name='MeanCartRecommendation',
        ),
    ]
