# Generated by Django 3.2.18 on 2023-04-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeitem',
            old_name='likestatus',
            new_name='likestatus',
        ),
    ]
