# Generated by Django 3.2.18 on 2023-04-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeitem',
            name='superlike',
        ),
    ]
