# Generated by Django 3.2.18 on 2023-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_remove_likeitem_superlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeitem',
            name='superliked',
            field=models.BooleanField(default=False),
        ),
    ]
