# Generated by Django 3.2.18 on 2023-04-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_likeitem_superliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='transaction_id',
        ),
    ]
