# Generated by Django 3.2.18 on 2023-04-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_auto_20230406_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedimage',
            name='product_test',
        ),
    ]
