# Generated by Django 3.2.18 on 2023-04-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0005_remove_recommendedimage_product_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
